dependencies:
  # - <org/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.5.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.0"
dotenv: .env
networks:
  # default:
  goerli:
    eth_usd_priceFeed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
  mainnet-fork-dev:
    eth_usd_priceFeed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
